version: '3.8'

services:

  nginx:
    build:
      dockerfile: ../nginx/Dockerfile
      context: ../build
    restart: always
    volumes:
      - ../nginx/run:/opt/run
    env_file:
      - ../build/nginx.env
