services:

  next:
    build:
      dockerfile: ./src/Dockerfile
      context: ..
    restart: always
    volumes:
      - ../src:/opt/app/src
    command: bash -c 'echo "running next in prod mode" && cd next && npx next build && npx next start -p 8001'

  # nginx:
  #   depends_on:
  #     - next
