services:

  worker:
    build:
      dockerfile: ./src/Dockerfile
      context: ..
    restart: always
    volumes:
      - ../src:/opt/app/src
    command: bash -c 'echo "running worker" && cd worker && npx nodemon ./worker.js'
